#!/usr/bin/env node

import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(SCRIPT_DIR, '..');

const LIMITS = [
    { file: 'AGENTS.md', max: 150 },
    { file: 'scratch/agent-loop.md', max: 140 },
    { file: 'docs/agent/memory-model.md', max: 90 },
    { file: 'docs/agent/using-the-harness.md', max: 120 },
    { file: 'docs/agent/script-reference.md', max: 90 },
    { file: 'docs/agent/loop-contract.md', max: 90 },
    { file: 'docs/agent/progress-model.md', max: 80 },
    { file: 'docs/agent/debugging.md', max: 80 },
    { file: 'docs/agent/roles.md', max: 80 },
];

function read(rel) {
    const p = path.join(ROOT, rel);
    return existsSync(p) ? readFileSync(p, 'utf8') : null;
}

function lineCount(text) {
    if (text == null) return 0;
    const trimmed = text.replace(/\r?\n$/, '');
    return trimmed ? trimmed.split(/\r?\n/).length : 0;
}

function checkGenerated(rel, marker) {
    const text = read(rel);
    if (text == null) return null;
    return text.includes(marker)
        ? null
        : { level: 'warn', file: rel, message: `missing generated marker "${marker}"` };
}

export function collectMemoryIssues() {
    const issues = [];

    for (const limit of LIMITS) {
        const text = read(limit.file);
        if (text == null) {
            issues.push({ level: 'warn', file: limit.file, message: 'missing file' });
            continue;
        }
        const count = lineCount(text);
        if (count > limit.max) {
            issues.push({
                level: 'warn',
                file: limit.file,
                message: `${count} lines exceeds budget ${limit.max}`,
            });
        }
    }

    for (const issue of [
        checkGenerated('scratch/divergence-inventory.md', 'Generated by'),
        checkGenerated('scratch/hack-debt.md', 'Generated by'),
    ]) {
        if (issue) issues.push(issue);
    }

    return issues;
}

export function renderMemoryLint(issues) {
    if (!issues.length) return 'memory-lint ok';
    const lines = [];
    lines.push(`memory-lint ${issues.length} issue(s)`);
    for (const issue of issues) {
        lines.push(`${issue.level.padEnd(5)} ${issue.file}: ${issue.message}`);
    }
    return lines.join('\n');
}

function main() {
    const strict = process.argv.includes('--strict');
    const issues = collectMemoryIssues();
    if (!issues.length) {
        console.log(renderMemoryLint(issues));
        return;
    }
    console.log(`memory-lint ${issues.length} issue(s)`);
    for (const issue of issues) {
        console.log(`${issue.level.padEnd(5)} ${issue.file}: ${issue.message}`);
    }
    if (strict) process.exit(1);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
    main();
}
